"""empty message

Revision ID: 4d75ac541568
Revises: dc5ff31b1927
Create Date: 2016-06-29 23:23:55.645642

"""

# revision identifiers, used by Alembic.
revision = '4d75ac541568'
down_revision = 'dc5ff31b1927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('scraped_dt', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'scraped_dt')
    ### end Alembic commands ###
