"""empty message

Revision ID: 521a7efe7f4b
Revises: 4d75ac541568
Create Date: 2016-07-02 12:34:54.250851

"""

# revision identifiers, used by Alembic.
revision = '521a7efe7f4b'
down_revision = '4d75ac541568'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'last_seen')
    ### end Alembic commands ###
