"""empty message

Revision ID: bb9f97cf66d7
Revises: c8161cd56b29
Create Date: 2016-07-06 18:39:13.479086

"""

# revision identifiers, used by Alembic.
revision = 'bb9f97cf66d7'
down_revision = 'c8161cd56b29'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.types import String

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('interest', sa.Boolean(), nullable=True),
    sa.Column('careers_url', sa.String(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(String(length=32)), nullable=True),
    sa.Column('locations', postgresql.ARRAY(String(length=32)), nullable=True),
    sa.Column('departments', postgresql.ARRAY(String(length=16)), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    ### end Alembic commands ###
