"""empty message

Revision ID: dc5ff31b1927
Revises: 8f44ee98cf02
Create Date: 2016-06-28 00:55:04.375257

"""

# revision identifiers, used by Alembic.
revision = 'dc5ff31b1927'
down_revision = '8f44ee98cf02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'status')
    ### end Alembic commands ###
